[project]
name = "resume-screening-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.1",
    "pymupdf>=1.26.3",
    "scikit-learn>=1.7.1",
    "spacy>=3.8.7",
    "streamlit>=1.47.1",
]
